disquaire_aguettaf/disquaire_aguettaf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from store import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^store/', include('store.urls', namespace='store')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

disquaire_aguettaf/store/urls.py
from django.conf.urls import url
from . import views # import views so we can use them in urls.


urlpatterns=[
    url(r'^$', views.listing, name="listing"), #"/store" will call the method "index" in "views.py"
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^search/$', views.search, name="search")
]
app_name = 'store'

disquaire_aguettaf/store/models.py
from django.db import models

# Create your models here.
"""
ARTISTS = {
    'francis-cabrel': {'name': 'Francis Cabrel'},
    'lej': {'name': 'Elijay'},
    'rosana': {'name': 'Rosana'},
    'maria-dolores-pradera': {'name': 'Maria Dolores Pradera'},
}

ALBUMS = [
    {'name': 'Sarbacane', 'artists' : [ARTISTS['francis-cabrel']]},
    {'name': 'La Dalle', 'artists' : [ARTISTS['lej']]},
    {'name': 'Luna Nueva', 'artists' : [ARTISTS['rosana'], ARTISTS['maria-dolores-pradera']]}
]
"""

class Artist(models.Model): #class = table : store_artist
    name = models.CharField(max_length=200, unique=True) # attribut = column

    def __str__(self):
        return self.name

class Contact(models.Model): #class = table : store_artist
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Album(models.Model):
    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()
    artists = models.ManyToManyField(Artist,related_name='albums', blank=True)

    def __str__(self):
        return self.title

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted = models.BooleanField(default=False)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    album =models.OneToOneField(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact.name

disquaire_aguettaf/store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Album, Artist, Contact, Booking
from django.template import loader

def index(request):
    albums = Album.objects.filter(available=True).order_by("-created_at")[:12]
    formatted_albums = ["<li>{}</li>".format(album.title) for album in albums]
    #message = """<ul>{}</ul> """.format("\n".join(formatted_albums))
    template = loader.get_template('store/index.html')
    #message = "Salut tout le monde !"
    context= {'albums':albums}
    return render(request, 'store/index.html', context)

def listing(request):
    albums = Album.objects.filter(available=True)
    #formatted_albums = ["<li>{}</li>".format(album.title) for album in albums]
    #message = """<ul>{}</ul> """.format("\n".join(formatted_albums))
    context= {'albums':albums}
    #albums = ["<li>{}</li>".format(album['name'])for album in ALBUMS]
    #message = """<ul>{}</ul>""".format("\n".join(albums))
    return render(request, 'store/listing.html', context)

def detail(request, album_id):
    album=Album.objects.get(pk=album_id)
    #id = int(album_id)
    #album = ALBUMS[id]
    #artists=album.artist.all() #pour recuperer tout les artists
    artists_name = " ".join([artist.name for artist in album.artists.all()])
    #artists = " ".join ([artist['name'] for artist in album['artists']])
    #message= "Le nom de l'album est {}. Il a été écrit par {}".format(album.title, artists)
    context= {
        'album_title':album.title,
        'artists_name' : artists_name,
        'album_id' : album.id,
        'thumbnail' : album.picture
    }
    return render(request, 'store/detail.html', context)

def search (request):
    #si on veut recuperer et juste afficher les paraametre cité dans la requete
    #obj=str(request.GET) # tout les parametres passés dans la requete
    #query = request.GET['query']
    #message= f"proprieté GET : {obj} et requete : {query}"
    #return HttpResponse(message)

    query = request.GET.get('query')
    if not query:
        #message = "Aucun artiste n'est demandé"
        albums = Album.objects.all()
    else:
        """albums =[
            album for album in ALBUMS
            if query in " ".join(artist['name'] for artist in album['artists'])
        ]"""
        albums = Album.objects.filter(title__icontains=query)

        if not albums.exists(): #len(albums) == 0:
            albums=Album.objects.filter(artists__name__icontains=query)

        if not albums.exists():
            message ="Misère de misère, nous n'avons trouvé aucun résultat !"
        else:
            albums = ["<li>{}</li>".format(album.title) for album in albums]
            message = """
                Nous avons trouvé les albums correspondant à votre requète ! Les voici :
                <ul>
                        {}
                </ul>
            """.format("</li><li>".join(albums))
        title = "Résultats pour la requete %s"%query
        context = {
        'albums': albums,
        'title': title
        }
    return render(request, 'store/search.html', context)

disquaire_aguettaf/store/templates/store/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'store/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Le bateau pirate</a></div>
    <div class="address-bar">Radio rock, Mer du nord (ou dans le 20e, à Paris)</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Le bateau pirate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'store:listing' %}">Tous nos disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
      <div class="row">
        <div class="box">
            {% block content%}{% endblock %}
        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p> Realised by <a href="https://www.linkedin.com/in/abdelkader-guettaf-b95b27196" target="_blank">Abdelkader GUETTAF</a> <br> Thanks to <a href="http://bit.ly/36nxNJS" target="_blank">Céline Martinet Sanchez</a> and <a href="https://www.openclassrooms.com" target="_blank">OpenClassrooms </a><br> To see my other projects :  <a href="https://gitlab.com/users/aguettaf/projects" target="_blank">My Gitlab</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

  </body>
</html>

disquaire_aguettaf/store/templates/store/index.html
{% extends 'store/base.html' %}

  {% block content %}

    Je me suis faufilé dans le gabarit parent. Salut!

    {% include 'store/list.html' %}

  {% endblock %}

disquaire_aguettaf/store/templates/store/list.html
On ne me laisse pas entrer par la porte? j'entre par la fenetre

  {% for album in albums %}
      <div class="col-sm-4 text-center">
          <a href="{% url 'store:detail' album_id=album.id %}">
            <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
          </a>
          <h3><a href="{% url 'store:detail' album_id=album.id %}">{{ album.title }}</a></h3>
          {% for artist in album.artists.all %}
              <p>{{ artist.name }}</p>
          {% endfor %}
      </div>
      {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
  {% endfor %}